config/routes.rb
Rails.application.routes.draw do

  resources :agents do
    patch "set_default"
    resources :contacts
  end

  root to: "agents#index"

end

app/models/agent.rb
class Agent < ActiveRecord::Base
  has_many :contacts, dependent: :destroy

  validates :name, :presence => true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :agent

  validates :name, :presence => true
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :find_agent, only: [:show, :edit, :update, :destroy]

  def new
    @agent = Agent.new
  end

  def create
    @agent = Agent.new(agent_params)
    if @agent.save
      flash[:success] = "Agent has been created."
      redirect_to @agent
    else
      flash[:warning] = "Agent has not been created."
      render :new
    end
  end

  def index
    @agents = Agent.all
  end

  def show
    #binding.pry
  end

  def edit
  end

  def update
    #binding.pry
    respond_to do |format|
      if @agent.update_attributes!(agent_params)
        #flash[:success] = "agent has been updated."
        format.html { redirect_to @agent, success: "Agent has been updated." }
        format.json { render :json => @agent }
      else
        #flash[:warning] = "agent has not been updated."
        format.html { render :edit, warning: "Agent has not been updated." }
        format.js { render :js => @agent.errors }
      end
    end
  end

  def destroy
    @agent.destroy
    flash[:success] = "agent has been deleted."
    redirect_to agents_path
  end

  private
    def agent_params
      params.require(:agent).permit(:name, :default_contact)
    end

    def find_agent
      @agent = Agent.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:warning] = "The agent you're looking for couldn't be found."
      redirect_to root_path
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_agent
  before_action :find_contact, only: [:show, :edit, :update, :destroy]

  def new
    @contact = @agent.contacts.build
  end

  def create
    @contact = @agent.contacts.build(contact_params)
    if @contact.save
      flash[:success] = "Contact has been created."
      redirect_to [@agent, @contact]
    else
      flash[:warning] = "Contact has not been created."
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @contact.update(contact_params)
      flash[:success] = "Contact has been updated."
      redirect_to [@agent, @contact]
    else
      flash[:warning] = "Contact has not been updated."
      render :edit
    end
  end

  def destroy
    @contact.destroy
    flash[:success] = "Contact has been deleted."
    redirect_to @agent
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :tel, :address)
    end

    def find_contact
      @contact = @agent.contacts.find(params[:id])
    end

    def set_agent
      @agent = Agent.find(params[:agent_id])

      rescue ActiveRecord::RecordNotFound
          flash[:warning] = "The agent you're looking for couldn't be found."
          redirect_to root_path
    end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/agents/_form.html.erb
<% if @agent.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @agent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div id="agent_form">
  <%= form_for @agent do |f| %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <%= f.submit %>
  <% end %>
</div>

app/views/agents/_set_default.html.erb
<!-- the select field seems won't be loaded correctly when just came from the agents list in the first place-->
<% if @agent.contacts.any? %>
  <div id="set_default">
  <%= form_for(@agent, remote: true, :html => { :'data-type' => 'json' }) do |f| %>
      <div class="errors"></div>
      <%= f.label :default_contact %>
      <%= f.select(
              :default_contact,
              options_for_select(@agent.contacts.collect {|c| [ c.name, c.id ] },
              @agent.default_contact ),
              { prompt: "Please select" }
      ) %>
    <% end %>
  </div><br/>

<% end %>

app/views/agents/_show_contacts.html.erb
<div id="agent_contacts">
  Contacts ~
  <ul>
    <% @agent.contacts.each do |contact| %>
      <li class="contact <%= "default" if contact.id == @agent.default_contact %>"
          id="<%= contact.id %>">
        <%= link_to contact.name, agent_contact_path(@agent,contact) %>
        <%= contact.tel %>
      </li>
    <% end %>
  </ul>
</div>

app/views/agents/edit.html.erb
<h1>Edit Agent <%= @agent.id %></h1>
<%= render "form" %>
<%= link_to "Cancel", agent_path(@agent) %>

app/views/agents/index.html.erb
<h1>Agents</h1>

<%= link_to "New agent", new_agent_path %>
<table class="table">
  <tr>
    <th>ID</th>
    <th>Agent Name</th>
  </tr>
  <% @agents.each do |agent| %>
    <tr>
      <td><%= agent.id %></td>
      <td><%= link_to agent.name, agent_path(agent) %></td>
    </tr>
  <% end %>
</table>

app/views/agents/new.html.erb
<h1>New Agent</h1>
<%= render "form" %>

app/views/agents/show.html.erb
<h1>Agent <%= @agent.id %></h1>
Name: <%= @agent.name %><br/>
<%= link_to "Add new contact", new_agent_contact_path(@agent) %>

<%= render "set_default" %>
<br/>
<%= render "show_contacts" %>

<%= link_to "Edit", edit_agent_path(@agent) %>
<%= link_to "Delete", agent_path(@agent), method: :delete, data: { :confirm => "Are you sure?" } %>
<%= link_to "Back to agent list", agents_path %>

app/views/contacts/_form.html.erb
<div id="contact_form">
  <%= form_for [@agent, @contact] do |f| %>
    <% if @contact.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @contact.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :tel %>
      <%= f.text_field :tel %>
    </p>
    <p>
      <%= f.label :address %>
      <%= f.text_field :address %>
    </p>
    <%= f.submit %>
  <% end %>
</div>

app/views/contacts/edit.html.erb
<h1>Contact <%= @contact.id %></h1>
<%= render "form" %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>
<%= render "form" %>

app/views/contacts/show.html.erb
<h1>Contact <%= @contact.id %></h1>
Name: <%= @contact.name %><br/>
Tel: <%= @contact.tel %><br/>
Address: <%= @contact.address %><br/>

<%= link_to "Edit", edit_agent_contact_path(@agent, @contact) %>
<%= link_to "Delete", agent_contact_path(@agent, @contact),
                      method: :delete, data: { :confirm => "Are you sure?" } %>
<%= link_to "Back to agent detail", agent_path(@agent) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AgentContact</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>
<%= yield %>

</body>
</html>